### ISSUE TITLE
release of .6

### ISSUE THREAD

**Issue by fscottfoti** [sunlightlabs/census#11]
I'm hoping to integrate this api into a library which is used to get census data into Pandas dataframes.  https://github.com/synthicity/popgen  The current version of this library on pypi seems to have a few issues, but the version in github seems to be fine.  Is there any way you guys could upload the latest version to pypi and call it a release?  Thanks!

**Comment by jcarbaugh** [comment]
Apologies for the terribly long delay. I'm working through PRs and open issues and should have a 0.8 release out this week. Thanks!
