### ISSUE TITLE
Parsing Variables Document (Client.fields)

### ISSUE THREAD

**Issue by joehand** [sunlightlabs/census#17]
In addition to issue #14, it looks like there are other issues parsing the variables documents in the `Client.fields` function. If I run it as is, the returned data is empty. It seems like the Census changed format for the XML document.

I [created a branch](https://github.com/joehand/census/tree/fields-json) using the JSON variable documentation instead of XML. Let me know if I should open a PR for that. (edit: went ahead and opened PR #18)

But I couldn't quite figure out what the old code was trying to return when `flat=False`. Right now I return the variables as a nested object, which seemed right for `flat=False`.

**Comment by jcarbaugh** [comment]
@joehand just got access to this repo again. Version 0.8 was pushed to PyPI today which includes your PR. Thanks!
