### ISSUE TITLE
Work with 2010-2014 ACS

### ISSUE THREAD

**Issue by stefancoe** [sunlightlabs/census#20]
Just wondering if you could add this capability. I know it was just released but we are going to be using it very soon. Thanks!
https://www.census.gov/programs-surveys/acs/news/data-releases/2014/release.html#par_textimage_9

-Stefan

**Comment by jcarbaugh** [comment]
@stefancoe some other people were nice enough to submit updates for this support and I've just pulled them in. I should have a release up at some point this week. Thanks!
