### ISSUE TITLE
Can you update on PyPi?

### ISSUE THREAD

**Issue by anthonyjpesce** [sunlightlabs/census#23]
It looks like 0.7 version there only supports 2013 ACS for ZCTAs

**Comment by datapolitan** [comment]
Looks like #19 covers this but hasn't been updated in a version 0.8. Pinged @jcarbaugh in the PR. Hopefully it gets pushed so we don't have to build from source.

**Comment by jcarbaugh** [comment]
@anthonyjpesce @datapolitan @rebeccawilliams: I just released 0.8 on PyPI. I no longer have access to the GitHub repo, so I haven't been able to push the latest code up here yet. Waiting to hear back on whether I can get access again or not.

Thanks!

**Comment by datapolitan** [comment]
Thanks for taking care of this @jcarbaugh. Is there going to be a process for handling this in the future?

**Comment by anthonyjpesce** [comment]
Thanks!
