### ISSUE TITLE
README should reflect 'Use acs5 instead of acs' DeprecationWarning

### ISSUE THREAD

**Issue by trawick** [sunlightlabs/census#25]
As of release 0.8, something like this in the README

```
c.acs.state(('NAME', 'B25034_010E'), states.MD.fips)
```

should be

```
c.acs5.state(('NAME', 'B25034_010E'), states.MD.fips)
```

Thanks!!!

**Comment by jcarbaugh** [comment]
Thanks for catching that! I've updated in 9d9415a and am going to push out 0.8.1 to PyPI right now.
